webapp/mainApp/urls.py
from django.urls import path, include

from . import views

app_name = 'mainApp'
urlpatterns = [
    path('', views.TemplateView.as_view(), name='index'),
]

webapp/mqttApp/urls.py
from django.urls import path

from . import views

app_name = 'mqttApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail')
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mqttApp/', include('mqttApp.urls')),
    path('mainApp/', include('mainApp.urls')),
    path('admin/', admin.site.urls),
]

webapp/mainApp/models.py
from django.db import models

# Create your models here.

webapp/mqttApp/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.


#for testing class

#IoT 데이터에를 객체화 하기 위하 클래스.
#시간 값을 센서에서 찍어서 올리는게 맞겠지?
class Data(models.Model):
    def __str__(self):
        return "time : {} temp {} : humid : {}".format(
            self.timestamp, self.temp, self.humid
        )
    timestamp = models.DateTimeField(auto_now=True)
    temp = models.FloatField(default=0)
    humid = models.FloatField(default=0)

class Device(models.Model):
    def __str__(self):
        return self.device_id
    
    device_id = models.CharField(max_length=100)
    #디바이스가 운영된 시간을 초단위 저장
    running_time = models.IntegerField(default=0)
    

webapp/mainApp/views.py
import random
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.views import generic

class TemplateView(generic.TemplateView):
    template_name = 'mainApp/index.html'
    print("hello!")

webapp/mqttApp/views.py
from typing import ContextManager
from django import template
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.views import generic
from .models import Data


class IndexView(generic.ListView):
    template_name = 'mqttApp/index.html'
    context_object_name = 'latest_data_list'

    def get_queryset(self):
        return Data.objects.order_by('-timestamp')[:50]

class DetailView(generic.DetailView):
    model = Data
    template_name = 'mqttApp/detail.html'

webapp/mainApp/templates/mainApp/index.html
<!DOCTYPE html>
<html>

<head>
  <style type="text/css">
    #map {
  height: 400px;
  width: 100%;
}
  </style>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDY9sKyb4Cv9YLWhAVn9U9konardJ6-TO0&callback=initMap&libraries=&v=weekly"
    defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.0/socket.io.js"
    integrity="sha512-kRhNKRilFJ0TuMUgQK5O+d7Mo09dCmHLsxZb7sIwLfqpcF78O0OrwlajiS85/KTXxCNpkanNN17eEwgFtlFneQ=="
    crossorigin="anonymous"></script>
  <!-- 합쳐지고 최소화된 최신 CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- 부가적인 테마 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script>
    var binder = io("http://3.34.87.77:9999/data");
    setInterval(function () {
      binder.emit('request', { 'time': Date.now() });
    }, 10000);
    setInterval(function () {
      binder.on('rtdata', function (data) {
        console.log('binder buffered: ', data)
        var target = document.getElementById('data_0')
        var target_2 = document.getElementById('data_1')
        target.innerHTML = data.data[0]
        target_2.innerHTML = data.data[1]
      });
    }, 10000);
  </script>
  <script>
function initMap() {
  const mylocation = { lat: 37.345647, lng: 126.731217 };
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 15,
    center: mylocation,
  });
  const marker = new google.maps.Marker({
    position: mylocation,
    map: map,
  });
}
  </script>
</head>

<body>
  <div class="page-header">
    <h1>실시간 데이터 mqtt <small>mqtt</small></h1>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#">실시간 mqtt</a></li>
        <li role="presentation"><a href="/mqttApp/">저장된 데이터</a></li>
      </ul>
    </div>
  </nav>

  <div class="jumbotron">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">실시간 온도</h3>
      </div>
      <div class="panel-body" id="data_0">
        온도
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">실시간 습도</h3>
      </div>
      <div class="panel-body" id="data_1">
        습도
      </div>
      <div id="map"></div>
    </div>
  </div>

</body>

</html>

webapp/mqttApp/templates/mqttApp/detail.html
<!DOCTYPE html>
<html>

<head>
    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="page-header">
        <h1> {{ data.timestamp }} 이 때의 값 </h1>
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav nav-tabs">
                <li role="presentation"><a href="/mqttApp/">뒤로가기</a></li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron">
        <ul class="list-group">

            <li class="list-group-item">온도 : {{ data.temp }}</li>
            <li class="list-group-item">습도 : {{ data.humid }}</li>

        </ul>
    </div>

</body>

</html>

webapp/mqttApp/templates/mqttApp/index.html
<!DOCTYPE html>
<html>
    <head>
        <!-- 합쳐지고 최소화된 최신 CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- 부가적인 테마 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="page-header">
            <h1>실시간 데이터 저장 결과 <small>mysql-db</small></h1>
          </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav nav-tabs">
                <li role="presentation" ><a href="/mainApp/">실시간 mqtt</a></li>
                <li role="presentation" class="active"><a href="#">저장된 데이터</a></li>
              </ul>
        </div>
    </nav>

    <div class="jumbotron">
        {% if latest_data_list %}
<ul class="list-group">
{% for data in latest_data_list %}
    <li class="list-group-item"><a href="{% url 'mqttApp:detail' data.id %}">{{ data.timestamp }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No data are available.</p>
{% endif %}
      </div>

    </body>
</html>